version: "3.8"
services:
  feeder_app:
    container_name: feeder_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - app_db
    networks:
      - app_network

  app_nginx:
    container_name: app_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - feeder_app
    environment:
      NGINX_FPM_HOST: feeder_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  app_db:
    container_name: app_db
    image: mysql:latest
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - app_network

  app_redis:
    container_name: app_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge